### ISSUE TITLE
Update table of contents

### ISSUE THREAD

**Issue by lakshya125** [lakshya125/py_beginners#119]
many new files have been added which are not in table of contents

Add them in readme.md using markdown language.

Star the repository if you found it helpful and to find it easily next year

**Comment by lakshya125** [comment]
@kishan3 @misterdabu @Charliiee @oprahadian

**Comment by NathanPang001** [comment]
Hello, can you assign me to this?

**Comment by Adegitetaiwo** [comment]
Hello, can you assign me to this?

**Comment by jratnani20** [comment]
hey @Adegitetaiwo i am intrested in this, can you please assign task to me.....thnks in advnc

**Comment by lakshya125** [comment]
🌟 Star the repository if you found it helpful and so you can find it easily nest year👻

**Comment by lakshya125** [comment]
I have not seen any pr related yo this issue . Does anyone want to do it . Just send the pr . You do not need to be assigned


@AmanDeep-21 @KwameTaylor @Adegitetaiwo @NathanPang001 @RishabhRyber   you guys can take a stab at it

**Comment by ViKrAm-Bais** [comment]
@lakshya125 I am interested, could you assign it to me ?

**Comment by xvidviii** [comment]
Hello, I sorted and added files to the table of contents. Do check it. #176

**Comment by KwameTaylor** [comment]
Thanks @lakshya125, I didn't have time this week, but glad to see that @xvidviii has taken care of it. :)
