### ISSUE TITLE
new ideas

### ISSUE THREAD

**Issue by lakshya125** [lakshya125/py_beginners#12]
Find new ideas for beginner level python code with a purpose. Create a pull request with the code.
See the repositery to find what we are looking for . Multiple people will be assinged.

**Comment by satyam12345678** [comment]
Doing it

**Comment by andikanugraha11** [comment]
Working for it

**Comment by ozamed** [comment]
I made an alarm clock for new idea sir

**Comment by ozamed** [comment]
@lakshya125 Sir i made an alarm clock and i made PR

**Comment by shalinipal69** [comment]
Hey, add hacktoberfest  in your repository's about section in the topic .

**Comment by ozamed** [comment]
@lakshya125 Hello, I made example for Speech To Text & Text To Speech and i made PR.

**Comment by Abirami-S21** [comment]
@lakshya125 Hi, I have added a 'word game' in python and made a PR #49 . Please, review and merge it. Thank you.

**Comment by oshyam** [comment]
Hello, I would like to contribute.
