### ISSUE TITLE
reverse string 

### ISSUE THREAD

**Issue by lakshya125** [lakshya125/py_beginners#31]
Write python code to reverse string input by user.
Check issues for completing hacktoberfest.
Do not forget to star the repository.

**Comment by TestPrab** [comment]
@lakshya125  Hi can I do this issue ?

**Comment by priyadarshan1995** [comment]
Hi @lakshya125 , Pls review this PR: https://github.com/lakshya125/py_beginners/pull/39 ?

**Comment by namita2310** [comment]
Hi @lakshya125 ,Please review my PR

**Comment by lakshya125** [comment]
Check out issues for more hactoberfest issues.
