### ISSUE TITLE
Create small python programs 

### ISSUE THREAD

**Issue by lakshya125** [lakshya125/py_beginners#61]
Find new ideas for beginner level python code with a purpose. 

Create a pull request with the code.

See the repositery to find what we are looking for .

 Multiple people will be assinged.

👨‍💻 Please  check your idea has not been.     done already 

Star ⭐ the repository if you liked it.

**Comment by kshsh00** [comment]
Can I be assigned to this??

**Comment by hardik-dadhich** [comment]
Hey, @lakshya125 Can I add some graph algos like count connected components In python?

**Comment by sawyer1997** [comment]
@lakshya125 I tried implementing list of all cuisines a city can offer, using 3rd party APIs. How does this sound ?

**Comment by kshsh00** [comment]
> Can I be assigned to this??

I have created a basic python code which downloads videos from youtube

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by lakshya125** [comment]
Thank you for your contributions.
Hope you completed Hactoberfest and had fun.
Star the repository if you found it helpful .
star the repository so that you can find it for next year. 

@kshsh00 @sawyer1997 @Shreyas-Gupta-21
