### ISSUE TITLE
👻 Last call for hactoberfest 

### ISSUE THREAD

**Issue by lakshya125** [lakshya125/py_beginners#93]
😎  Hactoberfest is coming to an end.

🤖   Submit your last pull requests

🤓   Create small python scripts without libraries and frameworks.

🤠   Do not do work that has already been  done .

⭐Star the repository so you can find it next year.

👻Happy Hacking👻

**Comment by misterdabu** [comment]
Please assign to me.

**Comment by lakshya125** [comment]
NOTE : Multiple people can be assigned

**Comment by raghuchandan1** [comment]
Can you assign this issue to me?

**Comment by sakshishreyaa** [comment]
assign this to me

**Comment by spartaabhishek** [comment]
can i contribute?

**Comment by Sumit2399** [comment]
Hi @lakshya125  ,added a PR request for Dijkstra’s shortest path algorithm .Hoping for merge soon.

**Comment by misterdabu** [comment]
Hi I've added a rainbow_hex script which returns the hex code for the colors of the rainbow given the english color. Please merge when you get a chance. Thanks.

**Comment by Shreyas-Gupta-21** [comment]
Hello @lakshya125 ,added 4 PR requests @100, @101, @103, @108. Please merge them when your available. Also
my PRs @89, @90, @91 were not merged could you have tell what is incorrect in them ?

**Comment by DiamondPurvis** [comment]
Hello I have added pull requests. @112, @113, @114, @115. Hoping for a merge 👍
